#!/usr/bin/env bash
# Runs every validation check in this project — the independent Python
# reference implementation, the synthetic-data tamper-detection check, and
# the JS unit test suite (which cross-checks the calculator against the
# Python-generated vectors) — and writes a summary of the real output to
# validation/results/SUMMARY.md. Never hand-edit that file; it is
# regenerated by this script from actual run results every time.
#
# Usage: bash validation/run_all.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_DIR="$REPO_ROOT/app"
RESULTS_DIR="$SCRIPT_DIR/results"
mkdir -p "$RESULTS_DIR"

STATUS=0
NPM_TEST_OUTPUT="$RESULTS_DIR/.npm_test_output.txt"

echo "== 1/4: regenerating independent Python reference vectors =="
( cd "$SCRIPT_DIR" && python3 reference_calcs.py )
REF_STATUS=$?
[ $REF_STATUS -ne 0 ] && STATUS=1

echo "== 2/4: regenerating synthetic test reports =="
( cd "$SCRIPT_DIR" && python3 make_synthetic.py )
SYNTH_STATUS=$?
[ $SYNTH_STATUS -ne 0 ] && STATUS=1

echo "== 3/4: running JS unit tests (methane calc cross-check, integrity, evidence status, storage migration) =="
( cd "$APP_DIR" && npm test 2>&1 ) | tee "$NPM_TEST_OUTPUT"
NPM_TEST_STATUS=${PIPESTATUS[0]}
[ $NPM_TEST_STATUS -ne 0 ] && STATUS=1

echo "== 4/4: running tamper-detection check on synthetic records =="
( cd "$SCRIPT_DIR" && python3 tamper_test.py )
TAMPER_STATUS=$?
[ $TAMPER_STATUS -ne 0 ] && STATUS=1

# --- Parse real output for the summary; never fabricate numbers here. ---
TEST_SUMMARY_LINE=$(grep -E "Tests +[0-9]+ (passed|failed)" "$NPM_TEST_OUTPUT" | tail -1)
VECTOR_COUNT=$(python3 -c "import json; print(json.load(open('$SCRIPT_DIR/test_vectors.json'))['vectors'].__len__())" 2>/dev/null || echo "unknown")
CALC_CHECK_ALL_PASSED=$(python3 -c "import json; print(json.load(open('$RESULTS_DIR/calculator_check.json'))['allPassed'])" 2>/dev/null || echo "unknown")
TAMPER_ALL_PASSED=$(python3 -c "import json; print(json.load(open('$RESULTS_DIR/tamper_check.json'))['allScenariosPassed'])" 2>/dev/null || echo "unknown")
SYNTHETIC_COUNT=$(python3 -c "import json; print(json.load(open('$SCRIPT_DIR/synthetic/synthetic_reports.json'))['recordCount'])" 2>/dev/null || echo "unknown")
GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

rm -f "$NPM_TEST_OUTPUT"

cat > "$RESULTS_DIR/SUMMARY.md" <<EOF
# Validation run summary

Generated by \`validation/run_all.sh\` at $GENERATED_AT. Every number below
is read from this run's actual output (\`validation/results/*.json\`, the
Vitest run) — not hand-typed. Re-run the script to refresh it.

| Check | Result |
| --- | --- |
| Independent Python methane-calc reference vectors regenerated | $([ $REF_STATUS -eq 0 ] && echo "OK ($VECTOR_COUNT vectors)" || echo "FAILED") |
| JS calculator matches Python reference (1e-9 relative tolerance) | $CALC_CHECK_ALL_PASSED |
| JS unit test suite (Vitest) | $TEST_SUMMARY_LINE |
| Synthetic test reports generated | $([ $SYNTH_STATUS -eq 0 ] && echo "OK ($SYNTHETIC_COUNT records)" || echo "FAILED") |
| Tamper-detection check (all scenarios) | $TAMPER_ALL_PASSED |
| Manual offline/device trials | see \`validation/offline_trials.csv\` — **not yet run**, see \`docs/AUTHOR_ACTION_REQUIRED.md\` |

Detail files:
- \`validation/test_vectors.json\` — Python-generated reference vectors
- \`validation/results/calculator_check.json\` — per-vector JS-vs-Python comparison
- \`validation/synthetic/synthetic_reports.json\` — 100 fabricated test records
- \`validation/results/tamper_check.json\` — per-scenario tamper-detection results
- \`validation/results/offline_trials.csv\` — manual device trial log (author-completed)

Overall status: **$([ $STATUS -eq 0 ] && echo "PASS" || echo "FAIL — see individual check results above")**
EOF

echo
echo "Wrote $RESULTS_DIR/SUMMARY.md"
exit $STATUS
