import jsPDF from 'jspdf'

const MARGIN = 20
const PAGE_WIDTH = 210
const PAGE_HEIGHT = 297
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
const TOP_START = MARGIN + 8
const BOTTOM_LIMIT = PAGE_HEIGHT - MARGIN - 8

function ensureSpace(doc, y, needed) {
  if (y + needed > BOTTOM_LIMIT) {
    doc.addPage()
    return TOP_START
  }
  return y
}

function addParagraph(doc, y, text, { size = 10, lineHeight = 5, bold = false } = {}) {
  doc.setFont('helvetica', bold ? 'bold' : 'normal')
  doc.setFontSize(size)
  doc.setTextColor(20, 20, 20)
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH)
  let cursor = y
  lines.forEach((line) => {
    cursor = ensureSpace(doc, cursor, lineHeight)
    doc.text(line, MARGIN, cursor)
    cursor += lineHeight
  })
  return cursor
}

function addTable(doc, y, headers, rows) {
  let cursor = ensureSpace(doc, y, 8)
  const colWidth = CONTENT_WIDTH / headers.length
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(20, 20, 20)
  headers.forEach((h, i) => doc.text(String(h), MARGIN + i * colWidth, cursor))
  cursor += 5
  doc.setDrawColor(76, 175, 80)
  doc.line(MARGIN, cursor - 3, MARGIN + CONTENT_WIDTH, cursor - 3)
  doc.setFont('helvetica', 'normal')
  rows.forEach((row) => {
    cursor = ensureSpace(doc, cursor, 6)
    row.forEach((cell, i) => {
      const cellLines = doc.splitTextToSize(String(cell), colWidth - 2)
      doc.text(cellLines[0] ?? '', MARGIN + i * colWidth, cursor)
    })
    cursor += 5.5
  })
  return cursor + 2
}

export function generateReportPdf(sections, meta) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  doc.setProperties({
    title: meta.projectName,
    author: 'G-BioCred / Gideon Owhonda',
    subject: 'Biogas Feasibility Report',
    keywords: 'biogas, methane, carbon credits, IPCC, Nigeria',
  })

  let y = TOP_START

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(20, 90, 30)
  doc.text('G-BioCred', MARGIN, y)
  doc.setFontSize(11)
  doc.setTextColor(60, 60, 60)
  doc.text('Agro-Waste-to-Energy Feasibility Report', PAGE_WIDTH - MARGIN, y, { align: 'right' })
  y += 6
  doc.setFontSize(9)
  doc.text(`Date: ${meta.reportDateLabel}`, PAGE_WIDTH - MARGIN, y, { align: 'right' })
  y += 5
  doc.text(`Ref: G-BioCred-${meta.refHash}`, PAGE_WIDTH - MARGIN, y, { align: 'right' })
  y += 6
  doc.setDrawColor(76, 175, 80)
  doc.setLineWidth(0.6)
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y)
  y += 8

  y = addParagraph(doc, y, `Prepared for: ${meta.applicantName || 'Not specified'}`, { bold: true })
  y = addParagraph(doc, y, `Project: ${meta.projectName}`)
  y = addParagraph(doc, y, `Location: ${meta.location || 'Not specified'}`)
  y = addParagraph(doc, y, `Purpose: ${meta.purpose}`)
  y = addParagraph(
    doc,
    y + 2,
    'Prepared using G-BioCred v1.0 — An open-access biogas yield and carbon verification calculator developed at the NLNG Centre for Gas, Refining and Petrochemical Engineering, University of Port Harcourt.',
    { size: 9 },
  )
  y += 4

  sections.forEach((section) => {
    y = ensureSpace(doc, y, 14)
    y = addParagraph(doc, y + 2, section.title, { size: 13, bold: true, lineHeight: 6 })
    section.paragraphs.forEach((p) => {
      y = addParagraph(doc, y + 1, p)
    })
    if (section.table) {
      y = addTable(doc, y + 2, section.table.headers, section.table.rows)
    }
    if (section.footnote) {
      y = addParagraph(doc, y, section.footnote, { size: 8 })
    }
  })

  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(90, 90, 90)
    doc.text(`G-BioCred — ${meta.projectName}`, MARGIN, 12)
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 12, { align: 'right' })
    doc.setDrawColor(76, 175, 80)
    doc.setLineWidth(0.3)
    doc.line(MARGIN, 14, PAGE_WIDTH - MARGIN, 14)

    doc.text('Generated by G-BioCred v1.0 · gidoty.github.io/g-biocred · IPCC 2006/2019 Methodology', PAGE_WIDTH / 2, PAGE_HEIGHT - 10, {
      align: 'center',
    })
  }

  doc.save(`${meta.projectName.replace(/[^a-z0-9]+/gi, '-')}-gbiocred-report.pdf`)
}
